import os
import psycopg2
import bcrypt
# Automatically run database migrations on startup
def run_db_migrations():
    database_url = os.environ.get('DATABASE_URL')
    if not database_url:
        print("DATABASE_URL not found in environment variables. Skipping migration.")
        return

    commands = [
        """
        CREATE TABLE IF NOT EXISTS users (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(50) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        """,
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS user_id INT;",
        """
        DO $$ 
        BEGIN 
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_task') THEN
                ALTER TABLE tasks ADD CONSTRAINT fk_user_task FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
            END IF;
        END $$;
        """
    ]
    try:
        conn = psycopg2.connect(database_url)
        cur = conn.cursor()
        for command in commands:
            cur.execute(command)
        conn.commit()
        cur.close()
        conn.close()
        print("🚀 Database schema successfully updated via startup script!")
    except Exception as e:
        print(f"❌ Database migration failed: {e}")

# Trigger the setup function right away
run_db_migrations()
# 1. USER REGISTRATION ENDPOINT
@app.route('/api/register', methods=['POST'])
def register():
    data = request.get_json()
    username = data.get('username')
    password = data.get('password')

    if not username or not password:
        return jsonify({"error": "Username and password are required"}), 400

    # Securely hash the password
    bytes_password = password.encode('utf-8')
    salt = bcrypt.gensalt()
    password_hash = bcrypt.hashpw(bytes_password, salt).decode('utf-8')

    try:
        conn = get_db_connection() # Uses your existing connection helper
        cursor = conn.cursor()
        
        cursor.execute(
            "INSERT INTO users (username, password_hash) VALUES (%s, %s) RETURNING id;",
            (username, password_hash)
        )
        user_id = cursor.fetchone()[0]
        conn.commit()
        
        cursor.close()
        conn.close()
        return jsonify({"message": "User registered successfully", "user_id": user_id}), 201

    except psycopg2.errors.UniqueViolation:
        return jsonify({"error": "Username already exists"}), 400
    except Exception as e:
        return jsonify({"error": f"Registration failed: {str(e)}"}), 500


# 2. USER LOGIN ENDPOINT
@app.route('/api/login', methods=['POST'])
def login():
    data = request.get_json()
    username = data.get('username')
    password = data.get('password')

    if not username or not password:
        return jsonify({"error": "Username and password are required"}), 400

    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        cursor.execute("SELECT id, password_hash FROM users WHERE username = %s;", (username,))
        user_record = cursor.fetchone()
        
        cursor.close()
        conn.close()

        if user_record:
            user_id, stored_hash = user_record
            # Verify password match
            if bcrypt.checkpw(password.encode('utf-8'), stored_hash.encode('utf-8')):
                return jsonify({"message": "Login successful", "user_id": user_id}), 200
        
        return jsonify({"error": "Invalid username or password"}), 401

    except Exception as e:
        return jsonify({"error": f"Login failed: {str(e)}"}), 500
import os
from flask import Flask, jsonify, request
from flask_cors import CORS

app = Flask(__name__)
# Allow requests from your local machine and your upcoming Render frontend URL
CORS(app, resources={r"/api/*": {"origins": "*"}})

# Automatically switch between Render Cloud DB (PostgreSQL) and local DB (MySQL)
DATABASE_URL = os.environ.get('DATABASE_URL')

def get_db_connection():
    if DATABASE_URL:
        # Running in Render Cloud (using PostgreSQL)
        import psycopg2
        conn = psycopg2.connect(DATABASE_URL)
        return conn
    else:
        # Running locally (using MySQL)
        import mysql.connector
        conn = mysql.connector.connect(
            host=os.environ.get('DB_HOST', 'localhost'),
            user=os.environ.get('DB_USER', 'root'),
            password=os.environ.get('DB_PASSWORD', 'password'),
            database=os.environ.get('DB_NAME', 'todo_db')
        )
        return conn

# Helper function to create the table if it doesn't exist
def init_db():
    conn = get_db_connection()
    cursor = conn.cursor()
    if DATABASE_URL:
        # PostgreSQL syntax
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS tasks (
                id SERIAL PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                completed BOOLEAN DEFAULT FALSE
            );
        ''')
    else:
        # MySQL syntax
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS tasks (
                id INT AUTO_INCREMENT PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                completed BOOLEAN DEFAULT FALSE
            );
        ''')
    conn.commit()
    cursor.close()
    conn.close()

# Initialize the database table right away
try:
    init_db()
except Exception as e:
    print(f"Database initialization error: {e}")

@app.route('/api/tasks', methods=['GET'])
def get_tasks():
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        if DATABASE_URL:
            # PostgreSQL fetch
            cursor.execute('SELECT id, title, completed FROM tasks ORDER BY id ASC;')
            rows = cursor.fetchall()
            tasks = [{'id': row[0], 'title': row[1], 'completed': row[2]} for row in rows]
        else:
            # MySQL fetch
            cursor.execute('SELECT id, title, completed FROM tasks ORDER BY id ASC;')
            rows = cursor.fetchall()
            tasks = [{'id': row[0], 'title': row[1], 'completed': bool(row[2])} for row in rows]
            
        cursor.close()
        conn.close()
        return jsonify(tasks), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/api/tasks', methods=['POST'])
def add_task():
    data = request.get_json()
    if not data or 'title' not in data:
        return jsonify({'error': 'Title is required'}), 400
    
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        if DATABASE_URL:
            # PostgreSQL insert with returning ID
            cursor.execute('INSERT INTO tasks (title) VALUES (%s) RETURNING id;', (data['title'],))
            task_id = cursor.fetchone()[0]
        else:
            # MySQL insert
            cursor.execute('INSERT INTO tasks (title) VALUES (%s);', (data['title'],))
            task_id = cursor.lastrowid
            
        conn.commit()
        cursor.close()
        conn.close()
        
        return jsonify({'id': task_id, 'title': data['title'], 'completed': False}), 201
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    # Use port assigned by Render or default to 5000 locally
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
