import os
import psycopg2
from flask import Flask, jsonify, request
from flask_cors import CORS
from werkzeug.security import generate_password_hash, check_password_hash

# 1. INITIALIZE THE APP & CORS FIRST
app = Flask(__name__)
# Allow requests from your local machine and your upcoming Render frontend URL
CORS(app, resources={r"/api/*": {"origins": "*"}})

# Automatically switch between Render Cloud DB (PostgreSQL) and local DB (MySQL)
DATABASE_URL = os.environ.get('DATABASE_URL')

def get_db_connection():
    if DATABASE_URL:
        # Running in Render Cloud (using PostgreSQL)
        import psycopg2
        conn = psycopg2.connect(DATABASE_URL)
        return conn
    else:
        # Running locally (using MySQL)
        import mysql.connector
        conn = mysql.connector.connect(
            host=os.environ.get('DB_HOST', 'localhost'),
            user=os.environ.get('DB_USER', 'root'),
            password=os.environ.get('DB_PASSWORD', 'password'),
            database=os.environ.get('DB_NAME', 'todo_db')
        )
        return conn

# 2. RUN AUTOMATIC DATABASE MIGRATIONS ON STARTUP
def run_db_migrations():
    if not DATABASE_URL:
        print("DATABASE_URL not found in environment variables. Skipping migration.")
        return

    commands = [
        """
        CREATE TABLE IF NOT EXISTS users (
            id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username VARCHAR(50) NOT NULL UNIQUE,
            password_hash VARCHAR(255) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        """,
        "ALTER TABLE tasks ADD COLUMN IF NOT EXISTS user_id INT;",
        """
        DO $$ 
        BEGIN 
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_task') THEN
                ALTER TABLE tasks ADD CONSTRAINT fk_user_task FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
            END IF;
        END $$;
        """
    ]
    try:
        conn = psycopg2.connect(DATABASE_URL)
        cur = conn.cursor()
        for command in commands:
            cur.execute(command)
        conn.commit()
        cur.close()
        conn.close()
        print("🚀 Database schema successfully updated via startup script!")
    except Exception as e:
        print(f"❌ Database migration failed: {e}")

# Trigger the setup functions right away
try:
    run_db_migrations()
except Exception as e:
    print(f"Migration execution error: {e}")

# Helper function to create the table if it doesn't exist
def init_db():
    conn = get_db_connection()
    cursor = conn.cursor()
    if DATABASE_URL:
        # PostgreSQL syntax
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS tasks (
                id SERIAL PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                completed BOOLEAN DEFAULT FALSE,
                user_id INT
            );
        ''')
    else:
        # MySQL syntax
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS tasks (
                id INT AUTO_INCREMENT PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                completed BOOLEAN DEFAULT FALSE,
                user_id INT
            );
        ''')
    conn.commit()
    cursor.close()
    conn.close()

try:
    init_db()
except Exception as e:
    print(f"Database initialization error: {e}")


# 3. AUTHENTICATION ENDPOINTS

@app.route('/api/register', methods=['POST'])
def register():
    data = request.get_json()
    username = data.get('username')
    password = data.get('password')

    if not username or not password:
        return jsonify({"error": "Username and password are required"}), 400

    # Securely hash the password natively using Werkzeug (No external C dependencies)
    password_hash = generate_password_hash(password)

    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        cursor.execute(
            "INSERT INTO users (username, password_hash) VALUES (%s, %s) RETURNING id;",
            (username, password_hash)
        )
        user_id = cursor.fetchone()[0]
        conn.commit()
        
        cursor.close()
        conn.close()
        return jsonify({"message": "User registered successfully", "user_id": user_id}), 201

    except Exception as e:
        # Handle unique constraint violations gracefully
        if 'UniqueViolation' in type(e).__name__ or '1062' in str(e):
            return jsonify({"error": "Username already exists"}), 400
        return jsonify({"error": f"Registration failed: {str(e)}"}), 500


@app.route('/api/login', methods=['POST'])
def login():
    data = request.get_json()
    username = data.get('username')
    password = data.get('password')

    if not username or not password:
        return jsonify({"error": "Username and password are required"}), 400

    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        cursor.execute("SELECT id, password_hash FROM users WHERE username = %s;", (username,))
        user_record = cursor.fetchone()
        
        cursor.close()
        conn.close()

        if user_record:
            user_id, stored_hash = user_record
            # Safely verify the native password hash
            if check_password_hash(stored_hash, password):
                return jsonify({"message": "Login successful", "user_id": user_id}), 200
        
        return jsonify({"error": "Invalid username or password"}), 401

    except Exception as e:
        return jsonify({"error": f"Login failed: {str(e)}"}), 500


# 4. TASK MANAGEMENT ENDPOINTS

@app.route('/api/tasks', methods=['GET'])
def get_tasks():
    # Optional: Filter tasks by user_id if passed as a query parameter (?user_id=1)
    user_id = request.args.get('user_id')
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        if user_id:
            cursor.execute('SELECT id, title, completed, user_id FROM tasks WHERE user_id = %s ORDER BY id ASC;', (user_id,))
        else:
            cursor.execute('SELECT id, title, completed, user_id FROM tasks ORDER BY id ASC;')
            
        rows = cursor.fetchall()
        tasks = [{'id': row[0], 'title': row[1], 'completed': bool(row[2]), 'user_id': row[3]} for row in rows]
            
        cursor.close()
        conn.close()
        return jsonify(tasks), 200
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@app.route('/api/tasks', methods=['POST'])
def add_task():
    data = request.get_json()
    if not data or 'title' not in data:
        return jsonify({'error': 'Title is required'}), 400
        
    title = data['title']
    user_id = data.get('user_id') # Optional fallback for existing non-auth frontend implementations
    
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        
        if DATABASE_URL:
            # PostgreSQL insert with returning ID
            cursor.execute('INSERT INTO tasks (title, user_id) VALUES (%s, %s) RETURNING id;', (title, user_id))
            task_id = cursor.fetchone()[0]
        else:
            # MySQL insert
            cursor.execute('INSERT INTO tasks (title, user_id) VALUES (%s, %s);', (title, user_id))
            task_id = cursor.lastrowid
            
        conn.commit()
        cursor.close()
        conn.close()
        
        return jsonify({'id': task_id, 'title': title, 'completed': False, 'user_id': user_id}), 201
    except Exception as e:
        return jsonify({'error': str(e)}), 500


if __name__ == '__main__':
    # Use port assigned by Render or default to 5000 locally
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
